name: run_selenium 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run_selenium:
    name: run_selenium
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # set up chrome driver
      - name: setup
        run: sudo apt install python3-selenium
             cd /tmp
             wget https://dl.google.com/linux/linux_signing_key.pub
             sudo apt-key add linux_signing_key.pub
             echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
             sudo apt-get update
             sudo apt-get install google-chrome-stable
             
             google-chrome --version
             
      - name: module install
        run: pip install -r requirements.txt
         
      - name: main.py
        run: python main.py

      - name: scratchlanguage
        run: |
           cd testfile
           python _scratchlanguage.py
